name: Test Downstream Libraries - Slow

on: 
  workflow_call:
  workflow_dispatch:

env:
  PY_COLORS: 1

jobs:
  vegafusion:
     env:
       UV_SYSTEM_PYTHON: true

     strategy:
       matrix:
         python-version: ["3.11"]
         os: [ubuntu-latest]

     runs-on: ${{ matrix.os }}
     steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install uv
          uses: astral-sh/setup-uv@v6
          with:
            enable-cache: "true"
            cache-suffix: ${{ matrix.python-version }}
            cache-dependency-glob: "pyproject.toml"
        - name: clone-vegafusion
          run: |
              git clone --single-branch -b v2 https://github.com/vega/vegafusion.git
              cd vegafusion
              git log
        - name: Cache rust dependencies
          uses: Swatinem/rust-cache@v2
          with:
            workspaces: vegafusion
        - name: Build wheels
          uses: PyO3/maturin-action@v1
          with:
            command: build
            manylinux: 2014
            rust-toolchain: stable
            args: --release -m vegafusion/vegafusion-python/Cargo.toml --features=protobuf-src --strip
        - name: Install wheels
          working-directory: vegafusion/target/wheels/
          run: |
            ls -la
            python -m pip install vegafusion-*manylinux*.whl

            # Optional dependencies
            python -m pip install pyarrow pandas polars-lts-cpu "duckdb>=1.0" "vl-convert-python>=1.0.1rc1" scikit-image "pandas>=2.2" jupytext voila anywidget ipywidgets chromedriver-binary-auto

            # Test dependencies
            python -m pip install pytest altair vega-datasets scikit-image jupytext voila ipykernel anywidget ipywidgets selenium flaky tenacity chromedriver-binary-auto 
        - name: Test lazy imports
          working-directory: vegafusion/vegafusion-python/
          run: python checks/check_lazy_imports.py
        - name: Test vegafusion
          working-directory: vegafusion/vegafusion-python/
          env:
            VEGAFUSION_TEST_HEADLESS: 1
          run: pytest

  # build bokeh process emulating the build process used in the main bokeh repo
  # in order to tolerate possible updates in the .yaml files
  build-bokeh:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Clone Bokeh repository
        run: |
          git clone --single-branch -b branch-3.8 https://github.com/bokeh/bokeh.git
          cd bokeh
          git log --oneline -n 5
          
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          activate-environment: bk-test
          conda-remove-defaults: true
          
      - name: Install libmamba solver
        run: |
          conda install -q -n base conda-libmamba-solver
          conda config --set solver libmamba
          
      - name: Update bk-test environment
        working-directory: bokeh
        run: |
          conda env update -q -n bk-test -f conda/environment-build.yml
          
      - name: Install node modules
        working-directory: bokeh
        run: |
          bash scripts/ci/install_node_modules.sh
          
      - name: Build BokehJS
        working-directory: bokeh/bokehjs
        run: |
          node make build
          
      - name: Build pip packages
        working-directory: bokeh
        env:
          BOKEHJS_ACTION: 'install'
        run: |
          python -m build .
          
      - name: Verify pip install from sdist
        working-directory: bokeh
        run: |
          bash scripts/ci/verify_pip_install_from_sdist.sh
          
      - name: Verify pip install using sdist
        working-directory: bokeh
        run: |
          bash scripts/ci/verify_pip_install_using_sdist.sh
          
      - name: Verify pip install using wheel
        working-directory: bokeh
        run: |
          bash scripts/ci/verify_pip_install_using_wheel.sh
          
      - name: Build conda package
        working-directory: bokeh
        run: |
          bash scripts/ci/build_conda_package.sh
          
      - name: Verify conda install
        working-directory: bokeh
        run: |
          bash scripts/ci/verify_conda_install.sh
          
      - name: Upload wheel package
        uses: actions/upload-artifact@v4
        with:
          name: bokeh-wheel-package
          path: bokeh/dist/bokeh-*-py3-none-any.whl
          
      - name: Upload bokehjs package
        uses: actions/upload-artifact@v4
        with:
          name: bokehjs-package
          path: bokeh/bokehjs/build/dist/bokeh-bokehjs-*.tgz

  bokeh:
    needs: build-bokeh
    
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash -l {0}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Clone Bokeh repository
        run: |
          git clone --single-branch -b branch-3.8 https://github.com/bokeh/bokeh.git
          cd bokeh
          git log --oneline -n 5
          
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          activate-environment: bk-test
          conda-remove-defaults: true
          
      - name: Install libmamba solver
        run: |
          conda install -q -n base conda-libmamba-solver
          conda config --set solver libmamba
          
      - name: Update conda environment
        working-directory: bokeh
        run: |
          # Install conda dependencies using Bokeh's test environment
          conda env update -q -n bk-test -f conda/environment-test-${{ matrix.python-version }}.yml
          
      - name: Download wheel package
        uses: actions/download-artifact@v4
        with:
          name: bokeh-wheel-package
          path: bokeh/dist/
          
      - name: Install wheel package
        run: |
          pip install bokeh/dist/bokeh-*-py3-none-any.whl
          
      - name: Download bokehjs package
        uses: actions/download-artifact@v4
        with:
          name: bokehjs-package
          path: bokeh/bokehjs/build/dist/
          
      - name: Symlink bokehjs package
        working-directory: bokeh/bokehjs/build/dist/
        run: |
          ln -s $(ls -t bokeh-bokehjs-*.tgz | head -n 1) bokeh-bokehjs.tgz
          
      - name: List installed software
        run: |
          conda info
          conda list
          echo "node $(node --version)"
          echo "npm $(npm --version)"
          python --version
          
      - name: Install narwhals in development mode
        run: |
          pip install -e .
          
      - name: Ensure Python version
        run: |
          if [[ ! "$(python --version | cut -d' ' -f2)" == "${{ matrix.python-version }}"* ]]; then 
            echo "Python version mismatch!"
            python --version
            exit 1
          fi
          
      - name: Test Bokeh defaults
        working-directory: bokeh
        run: |
          pytest tests/test_defaults.py
          
      - name: Test Bokeh cross
        working-directory: bokeh
        run: |
          pytest tests/test_cross.py
          
      - name: Run Bokeh unit tests
        working-directory: bokeh
        if: success() || failure()
        run: |
          COLOR="--color=yes"
          COVERAGE="--cov=bokeh --cov-report=xml"
          POLICY="--last-failed --last-failed-no-failures none"
          pytest $COLOR $COVERAGE tests/unit || pytest $COLOR $POLICY tests/unit
          
